export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_CURRENCY_SYMBOL = "CHANGE_CURRENCY_SYMBOL";
export const SET_TRENDINGCOINS = "SET_TRENDINGCOINS";
export const SET_EXCHANGERATES = "SET_EXCHANGERATES";
export const SET_COINSLIST = "SET_COINSLIST";
export const SET_COINID = "SET_COINID";
